### ISSUE TITLE
Commons Lang 3 missing from Lib folder

### ISSUE THREAD

**Issue by giamma** [schemacrawler/SchemaCrawler#1560] opened 2024-05-24 08:40 UTC
### Description

The zip distribution is missing Commons Lang 3 from _schemacrawler/lib folder

### SchemaCrawler Version

16.21.2

### Java Version

17

### Operating System and Version

MacOS Sonoma

### Relational Database System and Version

Oracle 19c

### JDBC Driver and Version

21.11.00 as bundled with schemacrawler

**Comment by sualeh** [comment] 2024-05-27 20:54
@giamma How is this affecting your use of SchemaCrawler? This is not a runtime dependency of SchemaCrawler.

**Comment by giamma** [comment] 2024-05-28 07:34
Sorry, I did not put further details because I thought this was a trivial packaging mistake and you would be immediately aware of the issue.

In absence of commons-lang 3 I get a stacktrace at runtime due to a *NoClassDefFoundError* with the following commandline:

`./schemacrawler.sh  --log-level=CONFIG --url=myjdbcurl --user=user --password=pass --portable-names --info-level=standard --command=brief --output-file=schema.svg --output-format=svg`

`May 28, 2024 9:29:28 AM us.fatehi.utility.UtilityLogger logFatalStackTrace
SEVERE: Could not instantiate class schemacrawler.tools.commandline.command.AvailableServers: schemacrawler.schemacrawler.exceptions.InternalRuntimeException: Could not instantiate class <class schemacrawler.tools.commandline.command.AvailableServers>
picocli.CommandLine$InitializationException: Could not instantiate class schemacrawler.tools.commandline.command.AvailableServers: schemacrawler.schemacrawler.exceptions.InternalRuntimeException: Could not instantiate class <class schemacrawler.tools.commandline.command.AvailableServers>
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5687)
	at picocli.CommandLine$DefaultFactory.createCompletionCandidates(CommandLine.java:5677)
	at picocli.CommandLine$Model$ArgSpec$Builder.<init>(CommandLine.java:9576)
	at picocli.CommandLine$Model$OptionSpec$Builder.<init>(CommandLine.java:10137)
	at picocli.CommandLine$Model$OptionSpec$Builder.<init>(CommandLine.java:10114)
	at picocli.CommandLine$Model$OptionSpec.builder(CommandLine.java:9990)
	at picocli.CommandLine$Model$CommandReflection.buildArgForMember(CommandLine.java:12063)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:11965)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedMembers(CommandLine.java:11913)
	at picocli.CommandLine$Model$CommandReflection.extractArgGroupSpec(CommandLine.java:11793)
	at picocli.CommandLine$Model$CommandReflection.buildArgGroupForMember(CommandLine.java:12069)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:11947)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedMembers(CommandLine.java:11913)
	at picocli.CommandLine$Model$CommandReflection.extractArgGroupSpec(CommandLine.java:11793)
	at picocli.CommandLine$Model$CommandReflection.buildArgGroupForMember(CommandLine.java:12069)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:11949)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedMembers(CommandLine.java:11913)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11846)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6388)
	at picocli.CommandLine$Model$CommandReflection.buildMixinForMember(CommandLine.java:12054)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:11934)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedMembers(CommandLine.java:11913)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11846)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6388)
	at picocli.CommandLine.<init>(CommandLine.java:230)
	at picocli.CommandLine.<init>(CommandLine.java:224)
	at schemacrawler.tools.commandline.utility.CommandLineUtility.newCommandLine(CommandLineUtility.java:161)
	at schemacrawler.tools.commandline.SchemaCrawlerCommandLine.execute(SchemaCrawlerCommandLine.java:68)
	at schemacrawler.Main.main(Main.java:67)
Caused by: schemacrawler.schemacrawler.exceptions.InternalRuntimeException: Could not instantiate class <class schemacrawler.tools.commandline.command.AvailableServers>
	at schemacrawler.tools.commandline.state.StateFactory.create(StateFactory.java:55)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5683)
	... 28 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5658)
	at schemacrawler.tools.commandline.state.StateFactory.create(StateFactory.java:52)
	... 29 more
Caused by: schemacrawler.schemacrawler.exceptions.InternalRuntimeException: Could not load database drivers: org/apache/commons/lang3/StringUtils
	at schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry.loadJdbcDrivers(DatabaseConnectorRegistry.java:131)
	at schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry.<init>(DatabaseConnectorRegistry.java:141)
	at schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry.getDatabaseConnectorRegistry(DatabaseConnectorRegistry.java:61)
	at schemacrawler.tools.commandline.command.AvailableServers.availableServers(AvailableServers.java:42)
	at schemacrawler.tools.commandline.command.AvailableServers.<init>(AvailableServers.java:53)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at com.ing.data.cassandra.jdbc.utils.DriverUtil.safeParseVersion(DriverUtil.java:115)
	at com.ing.data.cassandra.jdbc.CassandraDriver.getMajorVersion(CassandraDriver.java:113)
	at schemacrawler.tools.databaseconnector.DatabaseConnectorRegistry.loadJdbcDrivers(DatabaseConnectorRegistry.java:123)
	... 40 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	... 43 more`

**Comment by sualeh** [comment] 2024-05-30 23:47
@giamma I am not able to reproduce the error using Java 17 on Windows. I do not have access to a Mac, but it should not really matter. Try removing the Cassandra driver from the lib folder. Please delete two jars files whose names start with "cassandra". Please let me know if that works.

**Comment by sualeh** [comment] 2024-06-18 01:16
Closing due to no activity.

**Comment by giamma** [comment] 2024-06-18 09:02
Hi, I confirm that after removing Cassandra jars from the lib folder I don't need commons lang 3 anymore.

**Comment by sualeh** [comment] 2024-08-05 01:15
Fixed in SchemaCrawler v16.22.2

**Closed by sualeh** 2024-08-05 01:15 UTC
Labels: :bug: bug
