### ISSUE TITLE
16.19.8 Upgrade issues

### ISSUE THREAD

**Issue by ajunwalker** [schemacrawler/SchemaCrawler#1053] opened 2023-03-22 00:49 UTC
### Description

After upgrading from 16.19.7 to 16.19.8, we seem to be getting an exception when analysing a SQL Server database with `SchemaCrawlerUtility.getCatalog(connSource, retrievalOpts, crawlerOpts, new Config(Map.of("load-row-counts", Objects.toString(context.isAnalyseRowCounts()))))`:

This was working perfectly fine before the patch release, so not sure what happened. 

### Relevant log output

```shell
Unexpected exception while analysing schema
schemacrawler.schemacrawler.exceptions.ExecutionRuntimeException: No matching schemas found
	at schemacrawler.crawl.SchemaCrawler.crawlSchemas(SchemaCrawler.java:274)
	at schemacrawler.crawl.SchemaCrawler.crawl(SchemaCrawler.java:149)
	at schemacrawler.tools.catalogloader.SchemaCrawlerCatalogLoader.loadCatalog(SchemaCrawlerCatalogLoader.java:51)
	at schemacrawler.tools.catalogloader.ChainedCatalogLoader.loadCatalog(ChainedCatalogLoader.java:76)
	at schemacrawler.tools.utility.SchemaCrawlerUtility.getCatalog(SchemaCrawlerUtility.java:110)
```

### SchemaCrawler Version

16.19.8

### Java Version

11.0.8

### Operating System and Version

MacOS

### Relational Database System and Version

SQL Server 15.00.4073

### JDBC Driver and Version

JDBC Driver 11.2 for SQL Server 11.2.0.0

**Comment by sualeh** [comment] 2023-03-22 00:52
@ajunwalker I cannot think of what might have caused this, so I will need the complete log output to investigate. Please take a look at [Guidelines for Support](https://www.schemacrawler.com/consulting.html) to provide logs.

**Comment by sualeh** [comment] 2023-03-22 14:11
@ajunwalker - have you tried reverting to the previous version of SchemaCrawler? I am wondering if this is due to a permissions issue with the database user that you are using to log into SQL Server.

**Comment by alwaysbemark** [comment] 2023-03-27 02:56
Hey @sualeh , we are pretty sure that the problem on our side starte due to the change in: https://github.com/schemacrawler/SchemaCrawler/pull/1042

We are using Regex inclusion/exclusion rules:
```
                    return new RegularExpressionRule(
                        // Inclusion
                        "DatabaseName\\..*",  

                       // Exclusion
                        ".*\\.sys|.*\\.cdc|.*\\.INFORMATION_SCHEMA" +
                        "|model\\..*|master\\..*|msdb\\..*|tempdb\\..*|rdsadmin\\..*" 
                    );
```

If we omit the inclusion, everything works and we see schemas retrieved (including the ones we want).
Any way we try to form the inclusion (tried `DatabaseName\\..*`, `^DatabaseName\\..*` and all possible combos), we get no schemas retrieved.

Note that the above works for us on 16.19.7 so my suspicion is that something is quoted when it shouldn't be or we are using the inclusion rules incorrectly. Would appreciate some help, thank you!

**Comment by sualeh** [comment] 2023-03-28 12:48
@ajunwalker Andrew, when you remove the exclusion rule, do you find that any of the schema names are getting quoted with double quotes that were not getting quoted before? Or the other way around - schema names that were quoted before that are no longer quoted? You will have to allow for these quotes in your regular expression. Please give me an example, so I can reproduce.

**Comment by alwaysbemark** [comment] 2023-03-28 23:50
Hey @sualeh , we managed to fix this by adding optional quotes to our `RegularExpressionRule` regexes:

`"['\"]*" + Pattern.quote(dbName) + "['\"]*";`

It seems that the schema names that are compared against the inclusion regexes are now escaped with quotes (they weren't before) so this was a breaking change for us. No biggie - it's fixed now. Thank you!

**Comment by sualeh** [comment] 2023-03-29 00:03
@alwaysbemark Thanks for sharing your regex. I would like to have a test case for this, since it was not caught by my SQL Server tests. Can you share the schema name, so I can create something similar for my tests?

**Comment by alwaysbemark** [comment] 2023-03-29 00:09
Heya, our database or schema names don't actually have any special characters, for our tests we have: `Northwind.dbo` for our schema names. 

We fetch the catalog using:

`final Catalog catalog = SchemaCrawlerUtility.getCatalog(connSource, retrievalOpts, crawlerOpts, config);`

and inside `SchemaCrawlerOptions` and `LimitOptionsBuilder#includeSchemas` we use:

```
new RegularExpressionRule(
                        // Inclusion regex
                        databaseName + "\\..*",

                       // Exclusion regex
                        ".*\\.sys|.*\\.cdc|.*\\.INFORMATION_SCHEMA" +
                        "|model\\..*|master\\..*|msdb\\..*|tempdb\\..*|rdsadmin\\..*"
                    );
``` 

Now we had to add the above pattern quoting `"['\"]*" + Pattern.quote(dbName) + "['\"]*";` to the databaseName. Hopefully this helps?

**Comment by sualeh** [comment] 2023-03-29 13:12
How are you creating the `SchemaRetrievalOptions` (`retrievalOpts`)? This will determine how the schemas get quoted. You can override the quoting method there, if you like, to go back to your old behavior.

**Closed as completed** 2023-03-30 12:16 UTC
Labels: :bug: bug

**Comment by csemrau** [comment] 2023-05-17 16:25
I had the same problem with getting back tick quotes after the update.

I investigated and debugged a bit and learned that the schema is checked twice and the inclusion rule must succeed both checks.
Unfortunately, the first check is hard-coded to use `Identifiers.STANDARD`, i.e. double quotes. Only the second check can be configured by specifying the identifiers in the `SchemaRetrievalOptions`. Setting the identifiers was tricky in itself, because you cannot set the `identifiers` directly on the options builder, but must use a workaround going through `identifierQuoteString` and a `fromConnection` call.

As an example, I set the identifier character to be "#" in the SchemaRetrievalOptions, and got this debug output:

```plain
s.inclusionrule.RegularExpressionRule: Including <"base-int"> since it matches /([#"`]?)\Qbase-int\E\1/
s.inclusionrule.RegularExpressionRule: Including <#base-int#> since it matches /([#"`]?)\Qbase-int\E\1/
```

Is this mixture of `Identifiers` usage intentional, or should it be considered a bug?


I opted to use a regex similar to one mentioned above and leave the SchemaRetrievalOptions untouched: 

    new RegularExpressionInclusionRule("([\"`]?)" + Pattern.quote(schema) + "\\1")

This accepts all three quotation variants I observed so far (no quotes, double quotes, back ticks) with balanced quotation, and escapes any funny characters within the schema name itself.

**Comment by csemrau** [comment] 2023-05-17 16:28
@alwaysbemark
> Heya, our database or schema names don't actually have any special characters, for our tests we have: `Northwind.dbo` for our schema names.

As it turns out, mixing lowercase and uppercase characters also triggers the quotes.
