### ISSUE TITLE
schemacrawler stuck on "Retrieving foreign keys" with MariaDB driver, works with MySQL driver

### ISSUE THREAD

**Issue by ogerardin** [schemacrawler/SchemaCrawler#1775] opened 2024-12-06 16:35 UTC
### Description

If I run exactly the same schemacrawler command against the same MariaDB database:

- with `--server mysql --host xxxx  --port xxxx` (thus using the MySQL driver) --> works as expected
- with `--url=jdbc:mariadb://xxxx` (thus using the MariaDB driver) --> gets stuck on "Retrieving foreign keys"

Using `--log-level=ALL` shows continuous activity which seems to indicate an infinite loop.

I'm using the official Docker image to run schemacrawler.

### How to Reproduce

First case (MySQL)
```
docker run --mount type=bind,source=$(pwd),target=/home/schcrwlr --rm -it schemacrawler/schemacrawler \
/opt/schemacrawler/bin/schemacrawler.sh --server 'mysql' --host xxxx --port=xxxx --user xxxx --password xxxx --schemas xxxx --info-level standard --log-level INFO --command schema 
```

Second case (MariaDB)
```
docker run --mount type=bind,source=$(pwd),target=/home/schcrwlr --rm -it schemacrawler/schemacrawler \
/opt/schemacrawler/bin/schemacrawler.sh --url=jdbc:mariadb://xxxx:xxxx/ --user xxxx --password xxxx --schemas xxxx  --info-level standard --log-level INFO --command schema
```

### Relevant log output

```shell
For confidentiality reasons I can't attach the full logs with --log-level=ALL
Here are the last lines with --log-level=INFO:

Dec 06, 2024 3:51:35 PM schemacrawler.crawl.PrimaryKeyRetriever retrievePrimaryKeys
INFO: Retrieving primary keys
Dec 06, 2024 3:51:35 PM schemacrawler.crawl.IndexRetriever retrieveIndexes
INFO: Retrieving indexes
Dec 06, 2024 3:51:35 PM us.fatehi.utility.scheduler.TaskDefinition lambda$new$0
INFO: Not running task <retrieveTableConstraints>
Dec 06, 2024 3:51:35 PM us.fatehi.utility.scheduler.TaskDefinition lambda$new$0
INFO: Not running task <retrieveTriggerInformation>
Dec 06, 2024 3:51:35 PM schemacrawler.crawl.ForeignKeyRetriever retrieveForeignKeys
INFO: Retrieving foreign keys


When using --log-level=ALL it loops over log messages similar to this one:

Dec 06, 2024 4:30:26 PM org.mariadb.jdbc.util.log.Slf4JLogger debug
FINE: execute query: SHOW CREATE TABLE `fctemp`.`T_CONTRACT_PTF_REJECTED_6751d6cd3b25a`
Dec 06, 2024 4:30:26 PM org.mariadb.jdbc.util.log.Slf4JLogger trace
FINEST: send: conn=565 (M)
       +--------------------------------------------------+
       |  0  1  2  3  4  5  6  7   8  9  a  b  c  d  e  f |
+------+--------------------------------------------------+------------------+
|000000| 43 00 00 00 03 53 48 4F  57 20 43 52 45 41 54 45 | C....SHOW CREATE |
|000010| 20 54 41 42 4C 45 20 60  66 63 74 65 6D 70 60 2E |  TABLE `fctemp`. |
|000020| 60 54 5F 43 4F 4E 54 52  41 43 54 5F 50 54 46 5F | `T_CONTRACT_PTF_ |
|000030| 52 45 4A 45 43 54 45 44  5F 36 37 35 31 64 36 63 | REJECTED_6751d6c |
|000040| 64 33 62 32 35 61 60                             | d3b25a`          |
+------+--------------------------------------------------+------------------+
```

### SchemaCrawler Version

16.22.2

### Java Version

Eclipse Adoptium OpenJDK 64-Bit Server VM 11.0.24+8

### Operating System and Version

Linux 5.15.167.4-microsoft-standard-WSL2

### Relational Database System and Version

MariaDB 10.6

### JDBC Driver and Version

mariadb-java-client-3.4.1.jar

**Comment by sualeh** [comment] 2024-12-07 19:41
@ogerardin I tried reproducing your issue with the SchemaCrawler Docker image, and I cannot reproduce it with the test database I use for testing. Please see https://www.schemacrawler.com/consulting.html for information on how to investigate further.

**Comment by sualeh** [comment] 2024-12-08 14:49
I will need the entire logs to help debug. Another way to debug is to give me a Docker image with a small database that can reproduce the issue.

**Comment by ogerardin** [comment] 2024-12-08 21:55
> I will need the entire logs to help debug. Another way to debug is to give me a Docker image with a small database that can reproduce the issue.

As mentioned there are confidentiality issues with the data so I can't hand it over to you. Plus it's a very big database...
I would need to take a subset, anonymize the data and hope I can reproduce the issue. Unfortunately I don't have a lot of time to spare for it, so as long as the mySQL driver works I can consider it a workaround :)

**Comment by sualeh** [comment] 2024-12-09 00:03
Sounds good. Closing the ticket.

**Closed by sualeh** 2024-12-09 00:03 UTC
Labels: :bug: bug
